version: 2

project_name: nodeisp

# setups builds for linux and darwin on amd64 and arm64
# https://goreleaser.com/customization/build
builds:
  - id: nodeispd
    main: ./cmd/nodeispd
    binary: nodeispd
    goos:
      - linux

    goarch:
      - amd64
      - arm64

    mod_timestamp: "{{ .CommitTimestamp }}"

    ldflags:
      - -s -w -X github.com/node-isp/node-isp/pkg/version.Version={{.Version}} -X github.com/node-isp/node-isp/pkg/version.Commit={{.Commit}} -X github.com/node-isp/node-isp/pkg/version.BuildDate={{ .CommitDate }}

  - id: nodeisp
    main: ./cmd/nodeisp
    binary: nodeisp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/node-isp/node-isp/pkg/version.Version={{.Version}} -X github.com/node-isp/node-isp/pkg/version.Commit={{.Commit}} -X github.com/node-isp/node-isp/pkg/version.BuildDate={{ .CommitDate }}

archives:
  - id: nodeisp
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - nodeisp
    format: binary
    files: [ ]

  - id: nodeispd
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - nodeispd
    format: binary
    files: [ ]

# create a source tarball
source:
  enabled: true
